### ISSUE TITLE
Configuration help on retronas

### ISSUE THREAD

**Issue by burritobike** [sairuk/cockpit-xboxmanager#3]
I built the necessary binaries but I can't seem to get it to connect. 

In the log on cockpit it says: /opt/xboxmanager/scripts/xboxmanager.sh exited with code 1

Trying to run it in terminal it outputs: Couldn't find extract-xiso, can't help you bro

I'm not sure where to go from here.

**Comment by sairuk** [comment]
what do you mean by you built the necessary binaries? 

There is a problem with the main branch version of the curlftpfs installer which has nothing to do with this project specficailly. The issue was recently fixed in the testing branch, you can switch to the testing branch through the Update menu and reinstall through retronas to get all the required tooling or install them manually.

extract-xiso is required by this tool, if it is not installed, install it along with curlftpfs the latter on deb12 is not available as a package and needs to be build manually.

**Comment by burritobike** [comment]
I built extract-xiso, but forgot to install it. I also built the stable branch of curlftpfs. xboxmanager connected afterward. 

It seemed to hang up part way through installing a game though I got some of the files transferred. Perhaps this is part of the curlftpfs bug? Some files managed to make it into the correct directory. It was hard to know what was going on without any kind of progress indicator.

 I attempted to grab the testing branch by going though the update menu(on retronas gui), but could only change the GIT branch from there. Is there another menu?

I'm on a debian 11 vm and quite new to it so I apologize.

**Comment by sairuk** [comment]
success of the tools will depend on the quality of the underlying connection, curlftpfs mounts the xbox ftp locally onto the retornas and then all the other tooling operate on the local mount.

for retronas, changing the git branch of retronas to testing is correct based on the intent of the information i gave, retronas has its own dependecy installers for this cockpit plugin and the installers are modified in retronas testing but if you have manually built and installed dependencies now you are operating outside of retronas supported model, retronas also targets deb12 these days.

**Comment by burritobike** [comment]
It looks like I will be best off starting a fresh VM. Thanks for your help and also for making this cool tool.

**Comment by sairuk** [comment]
Yeh, either way you have the basis installed already through building the tools, i'd expect it to work just as well either way.  As the readme says this is highly experimental, but good luck
